---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgDNIy8/X3tiQoZtZ/C0aBmZXw3dqBqHobWAGCEq0GQAgR5DwppY/WyutrnIzHiTRYQk/SlvVk5I9IopffgbWQkOWNoZr9rbpqN29QI05jAi53MaddAhLIYxY1hIGnlWTU9a2ox7Ds20NeFU5uofoUzihjuDIpBhJT2w656YHqBdBlCeleDiltYVQoAqCMUDtUNCZu+BWpacEC52XBaPyBRdgfSawmCdGz9yE7UbmMSg8h0tUgJFN17kT4pdwVrcIhntMm4a+9X+BQkIIHRoV9BEQGXrYqwEltxwYzuNXr4d4JQlWScmDigjx0SDDoVwokTdky+XBKhl+UifbyYZIZjdeAdyCM4YXHudE5EV0a2ytUr6pYFo+iGbEYuH7ps38IBk8niDsccwlctf7mFt0nwqQPp0U6rElhxer8ZHZI+KVcKMXiRN8DxaNpqXDcXHVDCIu/ozS0Cyf4+If0xtgSd3KrpviCvcofoyoyZ7uO1HDV3m+JUFzFvgPjNLSaWxo+qFmV0rYiCUJzXskRMZu/XfcjG2f4cVwI+976mojy6Zlq6n9XLfGQGkcb3rlkPvOzefga19JDAkAtjuID1U5XW9YhiyIxyZsaZlDgwHsvgJyGuaXMEV2DW6rF9EdhVBlKPBBIoJ7I6wbyHwAQzf578JCwehni7lsnlDybrU2SNarkDMdAEL/mZvbZSEj6sA4SnNNutM01GC3OZkdQjVIrZv+jKlRREvoO/n1H1mGbO901rSu2u0I8oRW0HTsQ==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
